### PR TITLE
Add CF_INSTANCE_INDEX and fix CF_INSTANCE_PORTS

### PR DESCRIPTION
**Pull request by st3v**
Small tweaks

### CODE REVIEW

**Comment by sclevine** [comment]
Good catch! `CF_INSTANCE_INDEX` is actually not declared for staging, but I'll remove it after merging.

**Comment by st3v** [comment]
Gotcha. 

What about `INSTANCE_INDEX` and `INSTANCE_GUID` btw? https://docs.run.pivotal.io/devguide/deploy-apps/environment-variable.html doesn't mention them.

**Comment by sclevine** [comment]
I did this by observation using a modified buildpack: https://github.com/sclevine/staticfile-buildpack
The docs aren't exact, and they don't cover env vars that are provided for legacy apps.

Here's staging:

```
CF_INSTANCE_ADDR=
CF_INSTANCE_IP=10.0.2.15
CF_INSTANCE_PORT=
CF_INSTANCE_PORTS=[]
CF_STACK=cflinuxfs2
HOME=/home/vcap
LANG=en_US.UTF-8
MEMORY_LIMIT=256m
OLDPWD=/home/vcap
PATH=/usr/local/bin:/usr/bin:/bin
PWD=/tmp/app
SHLVL=1
USER=vcap
VCAP_APPLICATION={"limits":{"fds":16384,"mem":256,"disk":512},"application_name":"testy","application_uris":["testy.local.pcfdev.io"],"name":"testy","space_name":"pcfdev-space","space_id":"29d4d545-dd0e-42a7-8516-0961eeeebba5","uris":["testy.local.pcfdev.io"],"application_id":"32d4590d-2af5-4ec7-8a6d-e59131e50559","version":"f4e0a783-c864-4870-8c09-9452b35d8669","application_version":"f4e0a783-c864-4870-8c09-9452b35d8669"}
VCAP_SERVICES={}
```

And launching:

```
CF_INSTANCE_ADDR=10.0.2.15:60006
CF_INSTANCE_GUID=f11f84e4-6f9c-424f-4954-904e59291e48
CF_INSTANCE_INDEX=0
CF_INSTANCE_IP=10.0.2.15
CF_INSTANCE_PORT=60006
CF_INSTANCE_PORTS=[{"external":60006,"internal":8080},{"external":60007,"internal":2222}]
HOME=/home/vcap/app
INSTANCE_GUID=f11f84e4-6f9c-424f-4954-904e59291e48
INSTANCE_INDEX=0
LANG=en_US.UTF-8
MEMORY_LIMIT=256m
PATH=/usr/local/bin:/usr/bin:/bin
PORT=8080
PWD=/home/vcap/app
SHLVL=1
TMPDIR=/home/vcap/tmp
USER=vcap
VCAP_APPLICATION={"application_id":"32d4590d-2af5-4ec7-8a6d-e59131e50559","application_name":"testy","application_uris":["testy.local.pcfdev.io"],"application_version":"f4e0a783-c864-4870-8c09-9452b35d8669","host":"0.0.0.0","instance_id":"f11f84e4-6f9c-424f-4954-904e59291e48","instance_index":0,"limits":{"disk":512,"fds":16384,"mem":256},"name":"testy","port":8080,"space_id":"29d4d545-dd0e-42a7-8516-0961eeeebba5","space_name":"pcfdev-space","uris":["testy.local.pcfdev.io"],"version":"f4e0a783-c864-4870-8c09-9452b35d8669"}
VCAP_SERVICES={}
```

And `VCAP_APPLICATION` for staging (via `jq -Sr`):

``` json
{
  "application_id": "32d4590d-2af5-4ec7-8a6d-e59131e50559",
  "application_name": "testy",
  "application_uris": [
    "testy.local.pcfdev.io"
  ],
  "application_version": "f4e0a783-c864-4870-8c09-9452b35d8669",
  "limits": {
    "disk": 512,
    "fds": 16384,
    "mem": 256
  },
  "name": "testy",
  "space_id": "29d4d545-dd0e-42a7-8516-0961eeeebba5",
  "space_name": "pcfdev-space",
  "uris": [
    "testy.local.pcfdev.io"
  ],
  "version": "f4e0a783-c864-4870-8c09-9452b35d8669"
}
```

And for launching:

``` json
{
  "application_id": "32d4590d-2af5-4ec7-8a6d-e59131e50559",
  "application_name": "testy",
  "application_uris": [
    "testy.local.pcfdev.io"
  ],
  "application_version": "f4e0a783-c864-4870-8c09-9452b35d8669",
  "host": "0.0.0.0",
  "instance_id": "f11f84e4-6f9c-424f-4954-904e59291e48",
  "instance_index": 0,
  "limits": {
    "disk": 512,
    "fds": 16384,
    "mem": 256
  },
  "name": "testy",
  "port": 8080,
  "space_id": "29d4d545-dd0e-42a7-8516-0961eeeebba5",
  "space_name": "pcfdev-space",
  "uris": [
    "testy.local.pcfdev.io"
  ],
  "version": "f4e0a783-c864-4870-8c09-9452b35d8669"
}
```

Let me know if anything else seems incorrect.

I'm curious, what's your use case for this?
I'm building a `cf local` CLI plugin that's more flexible and supports downloading and launching droplets from a real CF.

**Comment by st3v** [comment]
My use case: I want faster feedback when developing an app. I don't want to push to a real CF during development because that's too slow and at that stage I don't need most of the CF features (scaling, health checking, ...). 

Basically, I want a simple CF _simulator_, not a CF _emulator_. Services like MySQL, Redis, or Rabbit could be provided by separate containers that are bound to the app via `VCAP_SERVICES`.

I was thinking of writing something like that and talked to @flavorjones about it. He mentioned your project and it looks interesting. For my particular use case I probably wouldn't have gone with the standard buildpacks but something simpler, less flexible. Mainly to make compilation and startup even faster.

What's the use case you had in mind for this?

**Comment by sclevine** [comment]
Hey, sorry for the delay! Your use case fits under the umbrella of what I'm building.
The plugin I'm working on:
1. Will let you build and launch a droplet locally, without a real CF involved.
2. Will eventually let you mount a local directory into a Docker-ized app container for fast feedback.

I'll let you know as soon as I have some code on Github.

**Comment by sclevine** [comment]
By the way, this plugin is basically finished and lives here: https://github.com/sclevine/cflocal

**Pull request merged**
